### ISSUE TITLE
X-axis display is misleading

### ISSUE THREAD

**Issue by jojo4u** [tyrasd/taghistory#16]
In default zoom the x-axis labels are showing years like "2015 2016". Counter-intuitively the label "2016" signifies the value 2016-01-01 - I would expect 2016-07-01 as the middle of the year. I already spent half an hour looking for the wrong dates on features ;) The "axis tick marks" should be changed to an interval representation like the first picture here: http://www.jqwidgets.com/jquery-widgets-documentation/documentation/jqxchart/jquery-chart-axes.htm

**Comment by tyrasd** [comment]
That's true. Unfortunately, I don't see a way to center the x-axis tick labels around their dynamically rounded timespan in the graphing library [vega](https://github.com/vega/vega) which is used here. If you know a way to do this, please let me know!

Anyway, I have now slightly mitigated the problem by displaying the axis labels to the right of the ticks, indicating that the value *starts* from the respective tick onward:

![before](https://cloud.githubusercontent.com/assets/1927298/19030814/973de61e-8950-11e6-909f-cf6918364d75.png)
![after](https://cloud.githubusercontent.com/assets/1927298/19030813/972310f0-8950-11e6-97df-02d35747ea20.png)
