### ISSUE TITLE
check IE11 support

### ISSUE THREAD

**Issue by tyrasd** [tyrasd/taghistory#17]
see https://github.com/gravitystorm/openstreetmap-carto/issues/1630#issuecomment-244412874

**Comment by kocio-pl** [comment]
I don't know if you're aware of it, but there are free (as in beer) Windows virtual machines for testing different MSIE versions:

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by tyrasd** [comment]
@Ircama: IE11 should now work, can you double-check it please?

**Comment by Ircama** [comment]
> @Ircama: IE11 should now work, can you double-check it please? 

It works fine now. 
Thanks and congrats for this tool
