### ISSUE TITLE
service down?

### ISSUE THREAD

**Issue by sun-geo** [tyrasd/taghistory#29]
http://taghistory.raifer.tech/
_"page not found"_

**Comment by ximex** [comment]
works for me. (without update data since mid 2018)

**Comment by sun-geo** [comment]
Okay, thanks for checking/testing. Now it works for me again.
Maybe only temporary interruption.
=> closed

**Comment by sun-geo** [comment]
_"(without update data since mid 2018)"_

yes, it would be nice to have a fresh data update, see #10
;-)
