### ISSUE TITLE
Enable direct links to the graphs

### ISSUE THREAD

**Issue by morray** [tyrasd/taghistory#6]
Allow to set parameters via the URL. So links could be shared. Alternatively create a hash for a given configuration which could be shared.

**Comment by joostschouppe** [comment]
I don't understand. You closed both issues, but there is no solution for either? Or did you close them to indicate you won't fix them?

**Comment by matkoniecz** [comment]
This issue appears to be open.

**Comment by tyrasd** [comment]
this is now implemented in #27
